---
title: "on qc"
output: 
  html_document: 
    fig_height: 6
    fig_width: 9
---

## Preamble

A little trial on comparing the 2015 data from the 2016 vs 2017 datacall

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, error = FALSE)
```

```{r}
library(stringr)
library(viridis)
library(dplyr)
library(tidyr)
library(ggplot2)
library(maps)
library(mapdata)
```

## Larger area

```{r}
m <- map_data("world")

# ------------------------------------------------------------------------------------------
# Detect files to read
file2017 <- 
  dir("../spatialPolygonsProducts/shapefiles/_2017_ICES_VMS_Datacall_VMS/2016/", pattern = "shp", full.names = TRUE)
i <- str_detect(file2017, "PEL")
file2017 <- file2017[!i]

file2018 <- 
  dir("../spatialPolygonsProducts/shapefiles/_2018_ICES_VMS_Datacall_VMS/2016/", pattern = "shp", full.names = TRUE)
i <- str_detect(file2018, "PEL")
file2018 <- file2018[!i]

label <- tools::file_path_sans_ext(basename(file2017))

# Only do for aggregated fleet data
for (i in c(1, 3, 10, 12, 17)) {
  
  # ----------------------------------------------------------------------------------------
  # read in the data and make a long table 
  
  thisyear <- 
    rgdal::readOGR(file2018[i])@data %>%
    select(c_square, lon = mid_lon, lat = mid_lat, sar = SurfSAR, ssar = SubsurfSAR) %>% 
    mutate(c_square = as.character(c_square)) %>% 
    gather(variable, thisyear, -c(c_square, lon, lat))
  
  # Limit the upper value to exclude potential extreme values
  lastyear <- 
    rgdal::readOGR(file2017[i])@data %>% 
    select(c_square, lon = mid_lon, lat = mid_lat, sar = SurfSAR, ssar = SubsurfSAR) %>% 
    mutate(c_square = as.character(c_square)) %>% 
    gather(variable, lastyear, -c(c_square, lon, lat))
  
  d <-
    thisyear %>% 
    full_join(lastyear) %>% 
    mutate(diff = thisyear - lastyear,
           miss = ifelse(!is.na(diff), NA_real_,
                         ifelse(is.na(thisyear), 2018, 2017)),
           near = near(thisyear, lastyear, tol = 0.01)) %>% 
    tbl_df()
  
  p <-
    d %>% 
    ggplot() +
    geom_raster(aes(lon, lat, fill = diff)) +
    geom_raster(data = d %>% filter(miss == 2018), aes(lon, lat), fill = "green") +
    geom_raster(data = d %>% filter(miss == 2017), aes(lon, lat), fill = "yellow") +
    geom_polygon(data = m, aes(long, lat, group = group), fill = "grey") +
    coord_quickmap(xlim = range(d$lon), ylim = range(d$lat)) +
    scale_fill_gradient2() +
    facet_wrap(~ variable) +
    labs(x = NULL, y = NULL, fill = "dSAR",
         title = "This year - Last year",
         subtitle = paste0(label[i], ", green: values in 2017, not in 2018, yellow: values in 2018, not in 2017"))
  print(p)
  
  d <-
    d %>% 
    select(lon, lat, variable, thisyear, lastyear) %>% 
    gather(measure, value, c(thisyear, lastyear))
  p <-
    d %>% 
    filter(variable == "sar") %>% 
    #mutate(value = ifelse(value > quantile(value, 0.9999, na.rm = TRUE),
    #                      quantile(value, 0.9999, na.rm = TRUE),
    #                      value)) %>% 
    ggplot() +
    geom_polygon(data = m, aes(long, lat, group = group), fill = "grey") +
    geom_raster(aes(lon, lat, fill = value)) +
    scale_fill_viridis(option = "B", direction = -1) +
    coord_quickmap(xlim = range(d$lon), ylim = range(d$lat)) +
    facet_wrap(~ measure) +
    labs(x = NULL, y = NULL, fill = "SAR",
         title = "Surface SAR",
         subtitle = label[i])
    print(p)
    
    p <- 
      d %>% 
      filter(variable == "ssar") %>% 
      #mutate(value = ifelse(value > quantile(value, 0.9999, na.rm = TRUE),
      #                      quantile(value, 0.9999, na.rm = TRUE),
      #                      value)) %>% 
      ggplot() +
      geom_polygon(data = m, aes(long, lat, group = group), fill = "grey") +
      geom_raster(aes(lon, lat, fill = value)) +
      scale_fill_viridis(option = "B", direction = -1) +
      coord_quickmap(xlim = range(d$lon), ylim = range(d$lat)) +
      facet_wrap(~ measure) +
      labs(x = NULL, y = NULL, fill = "SAR",
           title = "Subsurface SAR",
           subtitle = label[i])
    print(p)
}
```

## Smaller area

```{r}

for (i in c(1, 3, 10, 12, 17)) {
  
  # ----------------------------------------------------------------------------------------
  # read in the data and make a long table 
  
  thisyear <- 
    rgdal::readOGR(file2018[i])@data %>%
    select(c_square, lon = mid_lon, lat = mid_lat, sar = SurfSAR, ssar = SubsurfSAR) %>% 
    mutate(c_square = as.character(c_square)) %>% 
    gather(variable, thisyear, -c(c_square, lon, lat))
  
  # Limit the upper value to exclude potential extreme values
  lastyear <- 
    rgdal::readOGR(file2017[i])@data %>% 
    select(c_square, lon = mid_lon, lat = mid_lat, sar = SurfSAR, ssar = SubsurfSAR) %>% 
    mutate(c_square = as.character(c_square)) %>% 
    gather(variable, lastyear, -c(c_square, lon, lat))
  
  d <-
    thisyear %>% 
    full_join(lastyear) %>% 
    mutate(diff = thisyear - lastyear,
           miss = ifelse(!is.na(diff), NA_real_,
                         ifelse(is.na(thisyear), 2018, 2017))) %>% 
    tbl_df() %>% 
    filter(lon > -12, lon < 18,
           lat >  25, lat < 62)
  
  p <-
    d %>% 
    ggplot() +
    geom_raster(aes(lon, lat, fill = diff)) +
    geom_raster(data = d %>% filter(miss == 2018), aes(lon, lat), fill = "green") +
    geom_raster(data = d %>% filter(miss == 2017), aes(lon, lat), fill = "yellow") +
    geom_polygon(data = m, aes(long, lat, group = group), fill = "grey") +
    coord_quickmap(xlim = range(d$lon), ylim = range(d$lat)) +
    scale_fill_gradient2() +
    facet_wrap(~ variable) +
    labs(x = NULL, y = NULL, fill = "dSAR",
         title = "This year - Last year",
         subtitle = paste0(label[i], ", green: values in 2017, not in 2018, yellow: values in 2018, not in 2017"))
  print(p)
  
  d <-
    d %>% 
    select(lon, lat, variable, thisyear, lastyear) %>% 
    gather(measure, value, c(thisyear, lastyear))
  p <-
    d %>% 
    filter(variable == "sar") %>% 
    #mutate(value = ifelse(value > quantile(value, 0.9999, na.rm = TRUE),
    #                      quantile(value, 0.9999, na.rm = TRUE),
    #                      value)) %>% 
    ggplot() +
    geom_polygon(data = m, aes(long, lat, group = group), fill = "grey") +
    geom_raster(aes(lon, lat, fill = value)) +
    scale_fill_viridis(option = "B", direction = -1) +
    coord_quickmap(xlim = range(d$lon), ylim = range(d$lat)) +
    facet_wrap(~ measure) +
    labs(x = NULL, y = NULL, fill = "SAR",
         title = "Surface SAR",
         subtitle = label[i])
    print(p)
    
    p <- 
      d %>% 
      filter(variable == "ssar") %>% 
      #mutate(value = ifelse(value > quantile(value, 0.9999, na.rm = TRUE),
      #                      quantile(value, 0.9999, na.rm = TRUE),
      #                      value)) %>% 
      ggplot() +
      geom_polygon(data = m, aes(long, lat, group = group), fill = "grey") +
      geom_raster(aes(lon, lat, fill = value)) +
      scale_fill_viridis(option = "B", direction = -1) +
      coord_quickmap(xlim = range(d$lon), ylim = range(d$lat)) +
      facet_wrap(~ measure) +
      labs(x = NULL, y = NULL, fill = "SAR",
           title = "Subsurface SAR",
           subtitle = label[i])
    print(p)
}
```

